### ISSUE TITLE
Feedback for ToDo tutorial

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/avaloniaui.net#128]
Hello!

Feedback for [ToDo tutorial](https://avaloniaui.net/docs/tutorial/)

This is a very good start guide. And I would like to improve it a little: 

This tutorial is based on the fact that we create a project based on the `avalonia.mvvm` template. But I wanted to do it without using ReactiveUI, using the `avalonia.app` template. And I was faced with the fact that I could not reproduce the ["Wiring up the Views"](https://avaloniaui.net/docs/tutorial/wiring-up-views), having received the following:
![изображение](https://user-images.githubusercontent.com/2669927/79078723-edc1b600-7d12-11ea-8de9-bcc939b8b770.png)

This happens because the  `avalonia.app` template does not have `ViewLocator`, as in [`avalonia.mvvm`](https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/343bc81df4d6500779410ea27516fea078de2729/app-mvvm/App.xaml#L5-L7). Finding and fixing the problem, I continued to the next ["Locating Views"](https://avaloniaui.net/docs/tutorial/locating-views) step... And then I was embarrassed :)

I would like you to review the restructuring of the tutorial so that this information is early 

Thanks!

**Comment by kekekeks** [comment]
We probably need to restructure the MVVM part of the tutorial into MVVM introduction and RxUI introduction. I. e.
1) explain what MVVM is
2) create an app with manual INPC implementation
3) show how to use helpers like `SetAndNotify<T>(ref T field, T value, [CallerMemberName]string name = null)`
4) show how to use Fody.PropertyChanged
5) introduce RxUI

@grokys

**Comment by grokys** [comment]
Yeah, intention in the tutorial was to show best practices and start people off on the right track, because I found too many tutorials for WPF taught the code-behind-first method of coding, starting users off on the wrong track for writing large applications.

However it seems that newcomers:

1. Don't understand what MVVM is (I tried to address this over at http://avaloniaui.net/docs/quickstart/mvvm but probably failed
2. Are confused by RxUI

I'm sure there are ways to introduce this stuff in a way that is palatable to new users, but I'm not sure how to do so, and I'm the only person writing documentation at the moment. I _really_ don't have time to spend re-writing the tutorial at the moment, so this is going to have to be done by someone else.
